apiVersion: v1
kind: Pod
metadata:
  name: simpleweb-env
  labels:
    app: simpleweb
spec:
  containers:
  - name: simpleweb
    image: codelieche/simpleweb:v1
    ports:
    - containerPort: 8080
    env:
    - name: INDEX_PAGE
      valueFrom:
        configMapKeyRef:
          name: codelieche         # 引用的ConfigMap的名称
          key: index.html          # 引用的ConfigMap下对应的键的值
