apiVersion: v1
kind: Pod
metadata:
  name: simpleweb
  labels:
    app: simpleweb
spec:
  containers:
  - name: simpleweb
    image: codelieche/simpleweb:v1
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    secret:                    # 采用Secret Volume
      secretName: codelieche   # Secret的名字
