apiVersion: v1
kind: Pod
metadata:
  name: simpleweb
  labels:
    app: simpleweb
spec:
  containers:
  - name: simpleweb
    image: codelieche/simpleweb:v1
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:               # 容器的挂载信息
    - name: data
      mountPath: /data/
  volumes:
  - name: data
    cephfs:
      monitors:                 # ceph集群的地址：数组
      - 192.168.6.166:6789
      - 192.168.6.167:6789
      - 192.168.6.168:6789
      user: cephfs              # ceph集群上创建的用户
      secretRef:                # ceph集群上的秘钥
        name: secret-cephfs
      readOnly: false
      path: /simpleweb          # 挂载cephFS的路径，默认是:/
