apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simpleweb-pvc
  labels:
    app: simpleweb
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteMany
  volumeName: simpleweb-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simpleweb-pv
  labels:
    app: simpleweb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  cephfs:
    monitors:             # ceph集群
    - 192.168.6.166:6789
    - 192.168.6.167:6789
    - 192.168.6.168:6789
    path: /                # 默认是根目录
    secretRef:             # ceph的秘钥
      name: secret-cephfs
    user: cephfs           # 默认是admin
  persistentVolumeReclaimPolicy: Retain    # 当申请被释放后，pv会被保留(不清除和删除)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb
  labels:
    app: simpleweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleweb
  template:                             # pod的模板
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:                       # 容器列表
      - name: simpleweb                 # 容器名称
        image: codelieche/simpleweb:v1  # 容器镜像
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: simpleweb
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: simpleweb-pvc      # 在pod中使用pvc的名字
---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb
  labels:
    app: simpleweb
spec:
  type: ClusterIP
  selector:
    app: simpleweb
  ports:
  - name: http
    targetPort: 8080
    port: 80
