apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  rules:
  - host: grafana.codelieche.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
